# This file contains recipies for bootstrapping a new (ubuntu) machine.
# To do that, I want to install:
# - git, gh, my .gitconfig
# - dotfiles (and my dotfiles)
# - neovim (and my dotfiles for neovim)
#
# Also, I want to add a user `marinegor` with sudo privileges.

TARGET_OS := if os() == "linux" { "Linux" } else if os() == "macos" { "macOS" } else if os() == "windows" { "Windows" } else { "Unknown OS" }

user:
  sudo useradd -m -s /bin/bash marinegor
  sudo usermod -aG sudo marinegor

install-git:
    if [ {{TARGET_OS}} == "Linux" ]; then sudo apt-get install -y git gh git-lfs; fi
remove-git:
    if [ {{TARGET_OS}} == "Linux" ]; then sudo apt-get remove -y git gh git-lfs; fi

install-apts:
    if [ {{TARGET_OS}} == "Linux" ]; then sudo apt-get install -y curl wget build-essential; fi
remove-apts:
    if [ {{TARGET_OS}} == "Linux" ]; then sudo apt-get remove -y curl wget build-essential; fi

install-uv:
    if ! command -v uv &> /dev/null; then curl -LsSf https://astral.sh/uv/install.sh | sh; fi
remove-uv:
    which uv && uv cache clean
    which uv && rm -fr "$(uv python dir)"
    which uv && rm -fr "$(uv tool dir)"

install-pixi:
    if ! command -v pixi &> /dev/null; then curl -fsSL https://pixi.sh/install.sh | sh; fi
remove-pixi:
    which pixi && pixi clean cache -y
    rm -r ~/.pixi

install-bun:
    if ! command -v bun &> /dev/null; then curl -fsSL https://bun.sh/install | bash; fi
remove-bun:
    rm -rf ~/.bun

install-uv-tools:
    uv tool install --force pre-commit
    uv tool install --force ruff
    uv tool install --force basedpyright
    uv tool install --force gpustat
    uv tool install --force ty
    uv tool install --force go-task-bin
remove-uv-tools:
    uv tool uninstall pre-commit
    uv tool uninstall ruff
    uv tool uninstall basedpyright
    uv tool uninstall gpustat
    uv tool uninstall ty
    uv tool uninstall go-task-bin

install-cargo-tools:
    cargo install just
    cargo install du-dust
    cargo install fd-find
    cargo install exa
    cargo install btm
    cargo install --locked --bin jj jj-cli
    cargo install starship --locked
    cargo install ripgrep
    cargo install zoxide --locked
remove-cargo-tools:
    cargo uninstall just
    cargo uninstall du-dust
    cargo uninstall fd-find
    cargo uninstall exa
    cargo uninstall btm
    cargo uninstall jj-cli
    cargo uninstall starship
    cargo uninstall ripgrep
    cargo uninstall zoxide

install-fzf:
    if ! command -v fzf &> /dev/null; then git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install --all; fi
remove-fzf:
    rm -rf ~/.fzf ~/.fzf.bash ~/.fzf.zsh

install-ohmyzsh:
    if ! [ -d ~/.oh-my-zsh ]; then sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"; fi
remove-ohmyzsh:
    which $(uninstall_oh_my_zsh) && uninstall_oh_my_zsh -y

install-all: install-git install-apts install-uv install-pixi install-bun install-uv-tools install-cargo-tools install-fzf install-ohmyzsh
remove-all: remove-git remove-apts remove-uv remove-pixi remove-bun remove-uv-tools remove-cargo-tools remove-fzf remove-ohmyzsh
