#!/usr/bin/env bash
# Generate syntax-highlighting colours for light + dark mode from two Chroma
# styles. Only token *colours* are kept: backgrounds/layout come from the
# theme, and bold/italic/underline are stripped (and typo's own black-and-white
# bold/italic rules are reset), so code is coloured but never bold or italic.
# The Error token is dropped too: chroma marks unparseable characters (e.g.
# progress-bar output inside python blocks) as errors, which github renders as
# red boxes.
#
# Dark rules apply when forced dark (`.dark` on <html>/<body>) or in `auto`
# mode when the OS prefers dark (`body:not(.light)`), same as typo's light/dark
# image handling.
#
# Usage: scripts/gen-chroma-css.sh <light-style> <dark-style>   (css on stdout)
# Styles: https://xyproto.github.io/splash/docs/
set -euo pipefail

light="${1:?light style}"
dark="${2:?dark style}"

tokens() {
  hugo gen chromastyles --style="$1" |
    grep -E '^/\* [A-Za-z]+ \*/ \.chroma \.[a-z0-9]+ \{' |
    grep -vE '^/\* (Error|LineLink|LineTableTD|LineTable|LineNumbersTable|LineNumbers|Line|CodeLine) \*/' |
    sed -E 's/(font-weight|font-style|text-decoration):[^;}]*;?//g; s/;[[:space:]]*\}/ }/' |
    grep -vE '\{[[:space:]]*\}'
}

cat <<EOF
/* Generated by \`task chroma\` (scripts/gen-chroma-css.sh $light $dark), do not edit. */

/* colours only: undo typo's bold/italic token styles */
.chroma span {
  font-weight: inherit !important;
  font-style: inherit !important;
  text-decoration: none !important;
}

/* light: $light */
$(tokens "$light")

/* dark (forced): $dark */
$(tokens "$dark" | sed 's/\.chroma /.dark .chroma /')

/* dark (auto + OS prefers dark): $dark */
@media (prefers-color-scheme: dark) {
$(tokens "$dark" | sed 's/\.chroma /  body:not(.light) .chroma /')
}
EOF
