#!/usr/bin/env bash
# Generate syntax-highlighting colours for light + dark mode from two Chroma
# styles. Only token colour rules are kept; backgrounds/layout come from the
# theme. Dark rules apply when typo forces dark (`body.dark`) or when it's in
# `auto` mode and the OS prefers dark (`body:not(.light)`), same as typo's
# light/dark image handling.
#
# Usage: scripts/gen-chroma-css.sh <light-style> <dark-style>   (css on stdout)
# Styles: https://xyproto.github.io/splash/docs/
set -euo pipefail

light="${1:?light style}"
dark="${2:?dark style}"

tokens() {
  hugo gen chromastyles --style="$1" |
    grep -E '^/\* [A-Za-z]+ \*/ \.chroma \.[a-z0-9]+ \{' |
    grep -vE '^/\* (LineLink|LineTableTD|LineTable|LineNumbersTable|LineNumbers|Line|CodeLine) \*/'
}

cat <<EOF
/* Generated by \`task chroma\` (scripts/gen-chroma-css.sh $light $dark), do not edit. */

/* light: $light */
$(tokens "$light")

/* dark (forced): $dark */
$(tokens "$dark" | sed 's/\.chroma /body.dark .chroma /')

/* dark (auto + OS prefers dark): $dark */
@media (prefers-color-scheme: dark) {
$(tokens "$dark" | sed 's/\.chroma /  body:not(.light) .chroma /')
}
EOF
